# Generated by Django 5.2 on 2025-10-12 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 12, 15, 44, 31, 877372, tzinfo=datetime.timezone.utc)),
        ),
    ]
