# Generated by Django 5.2 on 2025-10-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_project_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
